name: Go

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.16

      - name: Build Windows
        env:
          GOOS: windows
        run: go build -v -o out/windows/wg-manage.exe .

      - name: Build Linux amd64
        env:
          GOOS: linux
        run: go build -v -o out/linux-amd64/wg-manage .

      - name: Build Linux arm64
        env:
          GOOS: linux
          GOARCH: arm64
        run: go build -v -o out/linux-arm64/wg-manage .

      - name: Build Mac
        env:
          GOOS: darwin
        run: go build -v -o out/darwin/wg-manage .

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: wg-manage-linux-amd64
          # A file, directory or wildcard pattern that describes what to upload
          path: out/linux-amd64/*

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: wg-manage-linux-arm64
          # A file, directory or wildcard pattern that describes what to upload
          path: out/linux-arm64/*

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: wg-manage-darwin
          # A file, directory or wildcard pattern that describes what to upload
          path: out/darwin/*

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          name: wg-manage-windows
          # A file, directory or wildcard pattern that describes what to upload
          path: out/windows/*
